name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin-test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Resolve latest version
        id: version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(./bin/latest-stable)
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@v4
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: entire --version
          version: ${{ steps.version.outputs.version }}
