name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ./bin ./lib

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shfmt
        uses: mvdan/sh/cmd/shfmt@latest
        with:
          args: -d -i 0 -ci bin/* lib/*
